[package]
name = "cargo-nw"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/aspectron/cargo-nw"
documentation = "https://cargo-nw.aspectron.org"
authors = ["Anton Yemelyanov <anton.yemelyanov@gmail.com>", "Surinder Singh Matoo Mattaur <surinder83singh@gmail.com>"]
keywords = ["cargo", "subcommand", "installation", "package","nwjs","nw"]
categories = ["command-line-utilities", "development-tools::cargo-plugins", "development-tools::build-utils"]
exclude = ["/.*", "/test"]
description = """
Cargo subcommand for building Node Webkit application deployment packages
(redistributables) for Windows, MacOS and Linux.
"""

[features]
test = []
unix = []
standalone = []
multiplatform = []
default = []
# default = ["test"]
# default = ["test","unix"]
# default = ["test","unix","multiplatform"]

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
duct = "0.13.5"
toml = "0.5.9"
tokio = { version = "1.20.1", features = ["full"] }
serde = { version = "1.0.148" , features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
async-std = "1.12.0"
console = "0.15.0"
trauma = "2.1.1"
reqwest = "0.11.13"
home = "0.5.3"
cfg-if = "1.0.0"
flate2 = "1.0.25"
tar = "0.4.38"
zip = "0.6.3"
fs_extra = "1.2.0"
async-trait = "0.1.59"
image = "0.24.5"
regex = "1.7.0"
chrono = "0.4.23"
convert_case = "0.6.0"
ico = "0.2.0"
globset = "0.4.9"
sha2 = "0.10.6"
serde_yaml = "0.9.14"
question = "0.2.2"
walkdir = "2.3.2"
ignore = "0.4.18"
uuid = { version = "1.2.2", features = ["v4"] }

# [target.'cfg(target_os = "windows")'.dependencies]
# winres-edit = { path="../winres-edit" }
winres-edit = "0.1.0"

# [target.'cfg(target_os = "windows")'.dependencies.windows]
# # [dependencies.windows]
# version = "0.43.0"
# features = [
#     "Win32_Foundation",
#     "Win32_System_LibraryLoader",
#     "Win32_System_Diagnostics_Debug",
#     "Win32_System",
# ]
