
# nw.toml - for additional properties please see https://github.com/aspectron/cargo-nw

[application]
name = "$NAME"
version = "$VERSION"
title = "$TITLE"
organization = "Your Organization Name"

[description]
short = "..."
long = """
$DESCRIPTION
"""

[package]
# root = ""
# resources = "resources/setup"
# exclude = ["resources/setup"]
exclude = [{ glob = ["{src/*,target/*,test/*,resources/setup/*,*.lock,*.toml,.git*}"] }]

[node-webkit]
version = "0.71.0"
ffmpeg = false

[macos-disk-image]
# window = ["0,0,300,300"]
# icon = ["0,0"]
# applications = ["0,0"]

[windows]
uuid = "$UUID"
group = "$GROUP"
# run_on_startup = "everyone"
run_after_setup = true

# [languages]
# languages = ["english"]

# [firewall]
# application = "in:out"
